### ISSUE TITLE
Addon TOC interface version (11400) is not compatible with the game version "classic" or was not found.

### ISSUE THREAD

**Issue by b-morgan** [BigWigsMods/packager#110]
Blizzard has released Classic Era version 1.14.0 (11400) and release.sh is testing for "113"* which, of course, fails.

**Comment by p3lim** [comment]
That must be very new, not even the wowinterface api has been updated:
https://api.wowinterface.com/addons/compatible.json

**Comment by Stanzilla** [comment]
Was released today, yeah

**Comment by Meorawr** [comment]
For what it's worth, you can avoid the issue by doing these two things:

- Using a client-specific interface version in your TOC file - `## Interface-Classic: 11400`
- Passing `-g classic` as a packager argument.

With both of the above the packager doesn't need to perform any pattern matching on interface versions to determine the target game type.

**Comment by b-morgan** [comment]
Currently my Github project, [Skillet-Classic](https://github.com/b-morgan/Skillet-Classic) contains two .toc files, Skillet-Classic.toc and Skillet-Classic-BCC.toc. The .zip file created by the packager (I currently pass "-g classic" to the packager) works for both versions although I do have to manually adjust the file that is uploaded to CurseForge to indicate it supports both.

@Meorawr, I'm not sure which of the two .toc files I should change to avoid this issue. Can you help me figure it out, please.

**Comment by Meorawr** [comment]
> @Meorawr, I'm not sure which of the two .toc files I should change to avoid this issue. Can you help me figure it out, please.

Taking a look at your project, unfortunately the solution presented above won't work.

Under normal circumstances you'd edit the main TOC file for your addon - "Skillet-Classic.toc" in your case - and do something similar [to what's shown here](https://github.com/WeakAuras/WeakAuras2/blob/009bf96e692abd8c32eced7a24d04c89acb6c44e/WeakAuras/WeakAuras.toc#L1-L3). During packagin, the packager would then rewrite the TOC to the correct interface version for the targeted game client - so if `-g classic` were passed it'd rewrite the linked TOC to say "Interface: 11307".

The issue is that your project name ends in "-Classic", which makes the packager [fall foul of another check elsewhere](https://github.com/BigWigsMods/packager/blob/de9cb3c680e30ae0823899e8915fd3f6d3d311c5/release.sh#L1502) and not do the rewrite; the reasoning being that a "-Classic" project suffix conflicts with the client-specific TOC file suffix implemented by Blizzard, and the packager opts to avoid rewriting versions in those.

You're probably going to have to wait for the pattern issue to be resolved.

**Comment by nebularg** [comment]
Updated the checks, thanks

**Comment by nebularg** [comment]
Just noticed the other issue, I'll have to look a see if there's a better way to handle other TOCs
