### ISSUE TITLE
WoWInterface uploading for both game versions

### ISSUE THREAD

**Issue by p3lim** [BigWigsMods/packager#33]
CurseForge handles multiple versions per project quite well (e.g. if you upload both classic and retail for the same version of a project, it'll display them separate), but WoWI doesn't handle this well.

An option to _not_ upload to an already configured (by TOC) remote (e.g. the oposite of the -p and -w flags, maybe uppercase) would help this issue in the short run.

**Comment by Nevcairiel** [comment]
The hack I currently use for this is to unset the WoWI Upload token for the classic build, eg:
https://github.com/Nevcairiel/Quartz/blob/master/.travis.yml#L14

For the record, WoWI is working on retail+classic on the same project as well.

**Comment by p3lim** [comment]
With that branch, how would it work/look on WoWI? Thanks for the workaround, I'll use that for now.

**Comment by p3lim** [comment]
Relevant discussion: https://www.wowinterface.com/forums/showthread.php?t=57394

**Comment by nebularg** [comment]
When uploading both to WoWI it looks like this:

![wowi](https://i.imgur.com/Ow6R9mD.png)

The reason I put it in it's own branch for now is switching to using the `updatefile_classic` api form field will leave the retail file there with no way to hide it since you're suppose to only use `updatefile` for single release projects.

I suggested to Dolby that he use the game version for selecting the release type so I can always use `updatefile` in the script and the site figures out the rest :p If that happens I won't have to change anything

**Comment by nebularg** [comment]
I also pushed being able to use `-w 0` to unset the id

**Comment by nebularg** [comment]
Gonna close this since WoWI supports both now without anything special
