### ISSUE TITLE
Request: CLI parameter to override the tag and upload as release/beta/alpha

### ISSUE THREAD

**Issue by teelolws** [BigWigsMods/packager#65]
Can I get an option to specify in the CLI that I want it to upload to curseforge as release/beta/alpha, ignoring what is written in the tag / absence of a tag?

Something like release.sh -n alpha

**Comment by exochron** [comment]
I'd like to have that as well. :)
My reason behind it is that a lot of bugs/errors don't happen on my client during development. So after I release some new version it can actually crash on a lot of clients. I'd like to avoid that in the future.
So my goal is to publish a regular version as beta and let some friends and betas user check it out. After a few days without any reports, I would just switch the file type on curesforge up to release. Because I don't need to release another version if it doesn't contains any changes, right?

If you're looking into it, "file_type" is your internal variable for it.
Thank you!

**Comment by p3lim** [comment]
Please don't try to delete issues yourself, everything is kept for historical purposes.

**Comment by teelolws** [comment]
I no longer want this.

**Comment by p3lim** [comment]
So just close the issue, don't alter it.
