### ISSUE TITLE
Broken pipe error with toc formatting

### ISSUE THREAD

**Issue by QartemisT** [BigWigsMods/packager#85]
```
/home/runner/work/_actions/BigWigsMods/packager/master/release.sh: line 942: echo: write error: Broken pipe
/home/runner/work/_actions/BigWigsMods/packager/master/release.sh: line 958: echo: write error: Broken pipe
/home/runner/work/_actions/BigWigsMods/packager/master/release.sh: line 984: echo: write error: Broken pipe
```

The TOC file is;
```
## Interface: 90005
## Interface-Classic: 11306
## Interface-BC: 20501
```

**Comment by Molkree** [comment]
DBM team got these errors in their PvP package, see runs [here](https://github.com/DeadlyBossMods/DBM-PvP/runs/2251446244?check_suite_focus=true#step:5:10) and [here](https://github.com/DeadlyBossMods/DBM-PvP/runs/2251461097?check_suite_focus=true#step:5:10).
As a result, all packages uploaded to CF had retail toc (including classic and tbc):

![image](https://user-images.githubusercontent.com/12860284/113443550-e0f21280-93fa-11eb-8b8f-23753e8837d3.png)
![image](https://user-images.githubusercontent.com/12860284/113443568-e6e7f380-93fa-11eb-9bf7-9c08e8b54b09.png)

I have tried to recreate this issue by using Interface/Interface-Classic/Interface-BC as in DBM-PvP with ATT addon and [couldn't](https://github.com/Molkree/AllTheThings/actions/runs/712401187), everything worked correctly. So there must be some other factor at play.

**Comment by nebularg** [comment]
hmm, this is because the toc file has a bom

**Comment by nebularg** [comment]
So the broken pipe error is unrelated and doesn't affect anything. It just means stdin closes before echo is done. I'm not sure why it's causing an error, but I switched the syntax so that doesn't show up in logs.

Interface not getting updated was because of the BOM in your TOC file.  I use `^## Interface` for the replacement, which won't match on the first line with BOM. (You should really remove the BOM from all the files)
