### ISSUE TITLE
Automatic population of most recent toc version number

### ISSUE THREAD

**Issue by Jademalo** [BigWigsMods/packager#97]
I have an extremely simple addon, which I release for all 3 current versions.

At present, I have the following in my .toc;

```
## Interface: 90005
## Interface-Retail: 90005
## Interface-Classic: 11307
## Interface-BCC: 20501
```

I then have GitHub actions run for each of the 3 build types. 

However, I've found that the vast majority of updates to my addon are simply me updating the toc to the latest version. The code itself is pretty simple, and doesn't really ever need any tweaking. 

I don't know if it already is available as functionality, but it would be extremely useful to be able to automatically populate the most recent toc versions for the respective build targets. 

For my setup, this would mean that the branch would simply have to be tagged to build to the latest toc, instead of having to go and check the latest versions. 

Is there already functionality available to do this, or if not could it be considered?

Thanks

**Comment by Meorawr** [comment]
The immediate question that comes to mind is "what is the latest TOC"?

Let's take the current situation for example where 9.0.5 is the current live retail patch and 9.1.0 is on the PTR. If the packager were to fill in the interface version _right now_ for that client, which would it use? I imagine most people would say it should use 9.0.5, which then brings in the next issue - when does the PTR version become the latest?

If it does that switchover after the patch has gone live in a region I think the feature would prove largely useless; most developers aren't going to wait to push updates for their addons until after an arbitrary point of time just so that the packager can save them changing three characters, and if they get it wrong they'll just get annoyed that the interface version is incorrect in the resulting package requiring yet another release.

If instead it did that switchover a few days to a week beforehand then this still might be confusing for some people - particularly users - as the resulting package that they'd download during the window prior to the patch launch would be flagged as "out of date". There might also be cases where such a package actually isn't at all compatible with the next patch and having the interface version indicating otherwise through an automated mechanism would ultimately be wrong.

This is also complicated further by there being - to my knowledge - no indicator of what the latest version actually is with respect to a live or in-test client. [As an example for the wowinterface endpoint](https://api.wowinterface.com/addons/compatible.json) for its supported versions, there's nothing there that could reasonably tell the packager that the 9.1 interface version right at this moment isn't the latest. Further even if an external source did have that information you'll still run into issues of how the packager would behave should that source be incorrect - there's been numerous occasions where the addon hosting platforms have managed to forget to update their version listings until after a patch has gone live.

**Comment by Jademalo** [comment]
Thanks for the detailed response, I'd clearly not considered enough!

I've never personally pushed updates to my addons until after a given patch had gone live, so that entire aspect entirely slipped my mind as an issue.  
The obvious answer could be flags to designate a PTR build or a live build and have parallel actions set up depending on if there was a push via say a tag or to a non-primary branch, though that very quickly obviously becomes more complicated than just changing the numbers. That could work well from a development standpoint though, pushing automatic PTR builds as beta, and then manually throwing a tag for the release. Obviously then however the question becomes when to throw the tag, so it's mostly delaying the issue. Though you could argue that's an issue even with releasing manually too.

I will say that I'm surprised there isn't an available and consistent endpoint for that data, I would have assumed there would be. That's absolutely understandable as an issue.

Thanks for the detailed considerations and issues, again that's much appreciated.

**Comment by p3lim** [comment]
I made an action for updating the TOC versions not too long ago, it's still alpha quality and has a tendency to fail a bit, but you could try it out if you want: https://github.com/p3lim/toc-interface-updater

**Comment by Jademalo** [comment]
Oh awesome, this looks fantastic. I'll definitely give it a shot, thanks!

**Comment by nebularg** [comment]
I've avoided automating interface values with the packager itself, too much magic for my liking.  It's perfectly fine to create your own process for it, though 👍
