### ISSUE TITLE
Invalid argument -g when trying to release for multiple versions

### ISSUE THREAD

**Issue by Jademalo** [BigWigsMods/packager#98]
https://github.com/Jademalo/SurroundFix/actions/runs/862936499

I've got a workflow set up to release my addon. Currently I'm testing switching to a universal release based on the new spec from blizzard with separate .toc files. I'm currently testing this without actually uploading the addon, but making sure the script runs correctly with the workflow.

According to the Readme, it's possible to use multiple game versions in a comma delimited list as valid arguments. Doing this with the actual game versions with `-g 1.13.7,2.5.1,9.0.5` [works as expected](https://github.com/Jademalo/SurroundFix/actions/runs/862961377), however trying to specity `-g retail,classic,bcc` throws an error ` Invalid argument for option "-g" (retail)`

I don't know enough about the workings of the packager to understand this further, and I was under the assumption that if I specified all 3 version name flags that it would effectively result in the same outcome as specifying all 3 valid version numbers based on the Interface values in the master .toc file. Clearly this is not the case, but I figure that if this is a bug it's worth reporting. At the very least, the error message seems to be incorrect.

**Comment by Nevcairiel** [comment]
The entire ecosystem around using one package for all versions is not complete yet. CurseForge, for example, will not properly serve the mod to all clients, since their API can only express one game version per zip (even though the website lets you set that) 

The packager will be updated in the future to support creating such packages properly, including automatically creating the version-specific TOCs and processing them. But for that to really make sense, the ecosystem around that also needs to be updated.

**Comment by Jademalo** [comment]
Alright, no worries. I wasn't sure exactly how much the packager itself was actually being changed with this, and based on the readme I assumed this would "work" (at least, aside from issues with how sites themselves distribute).

Regardless, I'm still surprised that the script errors out there. I would've assumed that it was possible to specify multiple names or even a mix of names and numbers, and that the correct value just replaced the word with the number based on the toc.

**Comment by nebularg** [comment]
The reason setting multiple game types doesn't work is because the packager wouldn't know what to use as the game version for each because it only ever tries to target one version.  Whereas using -g with version numbers acts as an override, it doesn't need to parse anything from the addon to be able to tell the hosting site what is being uploaded.

In the end, it was just easy to clean up setting multiple versions to mimic what CurseForge allows on their website, so that's all I did 😝 I should have disabled it or at least removed the documentation when I found out the CurseForge client doesn't actually support it, but was hoping they would fix it. Spoilers: They didn't.

**Comment by p3lim** [comment]
So these options with the new distinct TOC files doesn't work at all on CurseForge?
![image](https://user-images.githubusercontent.com/26496/119603606-d26a1b00-bded-11eb-9ee6-be173968b10b.png)

**Comment by nebularg** [comment]
Nope. The API the client checks when updating only shows one version regardless of game type it's checking for, so if the API decided it's a BCC file, it'll never show an update for the other two. (At least that's my understanding from what @AcidWeb has said)

**Comment by AcidWeb** [comment]
Yep. These settings work only on the page. Underlying API return only one client version. This issue was introduced during implementing Classic support and has not been repaired since then.

**Comment by p3lim** [comment]
But if I were to run with `-g 1.13.7,2.5.1,9.0.5` (or hopefully at some point `-g retail,classic,bcc`) then release.sh will properly upload tagging it correctly for the website? Is it just an issue with the CurseForge Client API (e.g. for Overwolf)?

**Comment by nebularg** [comment]
@p3lim correct, uploading with multiple versions shows those versions appropriately on the website, it's just the client that can't handle it properly

**Comment by nebularg** [comment]
Going to close this now, everything should be supported now without manually setting versions
